### ISSUE TITLE
Field Injection

### ISSUE THREAD

**Issue by quiver4arrow** [Milad-Akarie/injectable#169]
I looked up the whole doc and found nothing for this kind of injection

After lots of searching, I realized I need to use `getIt<T>();` to perform this.

That would be great  some sort of annotation to do this e.g. what dagger hilt does `@Inject`

++ Instead of using `@Injectable` for factory why not go with `@factory`? that clears things up

**Comment by Milad-Akarie** [comment]
@abstract-arrow Dagger relies on filed injection because Android Activities + other android components are constructed/initialized by the system, and Flutter we construct everything our self. that being said, is there any good reason why we should work with field injection? 

regarding the naming of injectable I thought it should match the package name + I've always though factory is reserved keyword in dart and they just won't let me use it.

**Comment by abstract-arrow** [comment]
I usually use field injection inside State objects (most people use widget dependency injection e.g. BLoC, Provider, ... have widget di) But since I'm using my own state management technique it's more convenient to field inject inside Widgets

```
class _HomeScreenState extends State<HomeScreen> {
  
  final viewModel = getIt<HomeScreenViewModel>();

  @override
  Widget build(BuildContext context) {
    return Container(child: Text(userRepo.getUsername()));
  }
}
```

What you saying about `factory` makes sense.

**Comment by Milad-Akarie** [comment]
@abstract-arrow who's constructing `_HomeScreenState`? if we are doing field injection here you'd need to call an init function inside of `initState() ` passing in instance of _HomeScreenState.

**Comment by abstract-arrow** [comment]
afaik Hilt doesn't need `onCreate()`

```
// Adds di container to the class annotated with it
@AndroidEntryPonint()
class MyActivity : AppCompatActivity() {
  @Inject lateinit var viewModel: MyViewModel

  override fun onCreate() {
    // viewModel is ready to be used
  }
}
```

If I'm not mistaken field injection needs reflection so If Flutter doesn't support that maybe it's not possible.
