### ISSUE TITLE
How to define a not null @factoryParam?

### ISSUE THREAD

**Issue by jhancock4d** [Milad-Akarie/injectable#180]
I've turned on null safety (thanks!) but if my factory param is not null I get a null safety error in the generated code because the param is nullable. It would be very nice if it respected it and required the not null type.

Is there a way to do this?

**Comment by Milad-Akarie** [comment]
@jhancock4d The nullSafety version of get_it doesn't allow to register nullable types so I thought the same thing applied to factoryParams.

It shouldn't be hard to fix and it will be included in the next build. 
Thanks for reporting.

**Comment by Milad-Akarie** [comment]
@jhancock4d I just had a chance to look at the code and turns out Get_it kinda enforces us to pass nullable types and it makes perfect sense because  the parameters param1 and param2 in get(param1: .., param2: ..) are always optional/nullable. 
I'm adding an assertion to make sure factoryParams are always nullable. 
Closing this for now.
