### ISSUE TITLE
Increase code_builder version to ^4.0.0

### ISSUE THREAD

**Issue by enpiech** [Milad-Akarie/injectable#198]
build_runner just update to version 2.0.0, it's depend on code_builder ^4.0.0.

`Because no versions of injectable_generator match >1.2.2 <2.0.0 and injectable_generator 1.2.2 depends on code_builder ^3.7.0, injectable_generator ^1.2.2 requires code_builder ^3.7.0.
And because build_runner >=2.0.0 depends on code_builder ^4.0.0, injectable_generator ^1.2.2 is incompatible with build_runner >=2.0.0.
So, because finance_tracker depends on both build_runner ^2.0.1 and injectable_generator ^1.2.2, version solving failed.`

**Comment by piuskamil** [comment]
same problem. I cant run my project at all.

Because injectable_generator >=1.2.1 depends on code_builder ^3.7.0 and injectable_generator >=1.2.0-nullsafety <1.2.1 depends on dart_style ^1.3.14, injectable_generator >=1.2.0-nullsafety requires code_builder ^3.7.0 or dart_style ^1.3.14.
And because injectable_generator <1.2.0-nullsafety depends on glob ^1.1.7, every version of injectable_generator requires code_builder ^3.7.0 or dart_style ^1.3.14 or glob ^1.1.7.
And because build_runner 2.0.1 depends on both code_builder ^4.0.0 and dart_style ^2.0.0, if injectable_generator any and build_runner 2.0.1 then glob ^1.1.7.
And because build_runner 2.0.1 depends on glob ^2.0.0 and no versions of build_runner match >2.0.1 <3.0.0, injectable_generator is incompatible with build_runner ^2.0.1.
So, because ** depends on both injectable_generator any and build_runner ^2.0.1, version solving failed.
pub get failed (1; So, because ** depends on both injectable_generator any and build_runner ^2.0.1, version solving failed.)

**Comment by Milad-Akarie** [comment]
@enpiech @piuskamil done in injectable 1.3.0 thanks for your patience.
