### ISSUE TITLE
Error @lazySingleton - only factories can have parameters

### ISSUE THREAD

**Issue by ZavbakGit** [Milad-Akarie/injectable#251]
If I use the annotation - @lazySingleton, I get an error while generating the code:

only factories can have parameters
package: app_anit_flutter / data / api / api_data_source.dart: 13: 7

If I use @injectable then no error occurs.

```dart
@module
abstract class AppModule {
  
  //@lazySingleton
  @injectable 
  ApiDataSource getApiDataSource(@factoryParam AuthBaseModel? authBaseModel) =>
      ApiDataSource(authBaseModel);

  @lazySingleton
  AuthBaseModel getAuthBaseModel() => AuthBaseModel(
        password: dotenv.env['TEST_PASS'] ?? '',
        user: dotenv.env['TEST_USER'] ?? '',
      );
}


class ApiDataSource {
  final AuthBaseModel? _authBaseModel;

  // ApiDataSource(@factoryParam this._authBaseModel){
  //   _init();
  // }

  ApiDataSource(this._authBaseModel){
    _init();
  }

  late final Swagger api;


  void _init() {
    final client = ChopperClient(
      baseUrl: dotenv.env['API_URL']!,
      converter: CommonJsonSerializableConverter(),
      interceptors: [
        LoggerInterceptor(),
        AuthApiInterceptor(_authBaseModel),
      ],
    );
    api = Swagger.create(client);
  }


  static final commonJsonDecoder = CommonJsonDecoder(generatedMapping);
}
```

https://github.com/ZavbakGit/app_anit_flutter

**Comment by dan-leech** [comment]
I think it's senseless for Singletons, because a singleton is the only one instance of a class.
You need some kind of singleton factory which will be return a class instance with a param if it exists.
(I need this too)
I found some kind of solution [here](https://github.com/AndX2/ws_demo/blob/626eefd2699e0a3371f02f013d46d24870519d04/lib/repository/message_repository.dart). But I prefer to use injectable annotations for this. 

AlsoI think it's better to write to get_it for this enhancement.
