### ISSUE TITLE
Auto registering: How to ignore particular abstract classes

### ISSUE THREAD

**Issue by TabooSun** [Milad-Akarie/injectable#3]
Say that I have an abstract class: `ClearCacheService`, usually I want them to be implemented by concrete services.

`class SessionService implements ClearCacheService`
`class ProfileService implements ClearCacheService`

Is there anyway I can do to just ignore ClearCacheService?

**Comment by Milad-Akarie** [comment]
hmmmmm I honestly didn't consider this use case, because what I'd usually do is bind my abstract class to its implementations not inject the implementation directly to respect **Dependency Inversion** principle.
so in your case, this's what I'd do
```dart
@Bind.toNamedType(SessionService)
@Bind.toNamedType(ProfileService)
abstract class ClearCacheService {}
```
still, there might be use cases when you need to inject the implementation directly 
so I'll include an ignore_abstract_without_bind flag in the next build. 

Thanks for reporting.

**Comment by Milad-Akarie** [comment]
all abstract classes are now ignored unless you add the injectable annotation your self and ofcourse define a factoryMethod.
