### ISSUE TITLE
[Question] How I can register external service with abstract type?

### ISSUE THREAD

**Issue by deandreamatias** [Milad-Akarie/injectable#359]
### Context

I need register different external services for web and mobile platforms.
My currently solution is:

```dart
// edit_image_service.dart

export 'edit_image_service_mobile.dart'
    if (dart.library.html) 'edit_image_service_web.dart';
```

```dart
// i_edit_image_service.dart

abstract class IEditImageService {
  Future<XFile?> crop(Rect rect, Uint8List rawImage);
}
```

```dart
// edit_image_service_mobile.dart

class EditImageService implements IEditImageService {

  @override
  Future<XFile?> crop(Rect rect, Uint8List rawImage) async {
    // ...implementation
  }
}
```

```dart
// edit_image_service_web.dart

class EditImageService implements IEditImageService {

  @override
  Future<XFile?> crop(Rect rect, Uint8List rawImage) async {
    // ...implementation
  }
}
```

```dart
// locator.dart

@module
abstract class RegisterModule {
  @Injectable(as: IEditImageService)
  EditImageService get getEditImageService => EditImageService();
}
```

### What I want

Register conditional (by platform) service by dependency injection, on RegisterModule. This will remove my conditional import on `edit_image_service.dart`.
I can't use environment, because I already use to identify the product environment (prod, staging, local).

### Problem

I try some like this:

```dart
// locator.dart

@module
abstract class RegisterModule {
  @Injectable(as: IEditImageService)
  IEditImageService get getEditImageService => kIsWeb ? EditImageServiceWeb() : EditImageServiceMobile();
}
```
But I can't return a abstract class on register module. Error:

```shell
[IEditImageService] is not a subtype of [IEditImageService]
package:flutter_base/common/interfaces/edit_image_service.dart:6:16
  ╷
6 │ abstract class IEditImageService {
  │                ^^^^^^^^^^^^^^^^^
  ╵
```

I really will appreciate if you have a solution for this case.
Thanks a lot

**Comment by yazanturk** [comment]
this problem shows when updating Flutter 3.10 any solution 
yazanturk@localhost ERP % flutter pub run build_runner build

Deprecated. Use `dart run` instead.
[INFO] Generating build script completed, took 158ms
[INFO] Reading cached asset graph completed, took 609ms
[INFO] Checking for updates since last build completed, took 700ms
[INFO] Running build completed, took 33ms
[INFO] Caching finalized dependency graph completed, took 240ms
[SEVERE] injectable_generator:injectable_builder on lib/core/network/api/task_list_api.dart (cached):

[TaskListApi] is not a subtype of [_TaskListApi]
package:cleancodeapp/core/network/api/task_list_api.dart:13:16
   ╷
13 │ abstract class TaskListApi {
   │                ^^^^^^^^^^^
   ╵
[SEVERE] injectable_generator:injectable_builder on lib/core/network/api/user_api.dart (cached):

[UserApi] is not a subtype of [_UserApi]
package:cleancodeapp/core/network/api/user_api.dart:9:16
  ╷
9 │ abstract class UserApi {
  │                ^^^^^^^
  ╵
[SEVERE] injectable_generator:injectable_builder on lib/core/network/api/stripe_payment_api.dart (cached):

[StripeApi] is not a subtype of [_StripeApi]
package:cleancodeapp/core/network/api/stripe_payment_api.dart:12:16
   ╷
12 │ abstract class StripeApi {
   │                ^^^^^^^^^
   ╵
[SEVERE] injectable_generator:injectable_builder on lib/core/network/api/ware_house_api.dart (cached):

[WareHouseApi] is not a subtype of [_WareHouseApi]
package:cleancodeapp/core/network/api/ware_house_api.dart:15:16
   ╷
15 │ abstract class WareHouseApi {
   │                ^^^^^^^^^^^^
   ╵
[SEVERE] injectable_generator:injectable_builder on lib/core/network/api/work_api.dart (cached):

[WorkApi] is not a subtype of [_WorkApi]
package:cleancodeapp/core/network/api/work_api.dart:24:16
   ╷
24 │ abstract class WorkApi {
   │                ^^^^^^^
   ╵
[SEVERE] injectable_generator:injectable_builder on lib/core/network/api/location_payment_api.dart (cached):

[LocationApi] is not a subtype of [_LocationApi]
package:cleancodeapp/core/network/api/location_payment_api.dart:11:16
   ╷
11 │ abstract class LocationApi {
   │                ^^^^^^^^^^^
   ╵
[SEVERE] injectable_generator:injectable_builder on lib/core/network/api/home_api.dart (cached):

[HomeApi] is not a subtype of [_HomeApi]
package:cleancodeapp/core/network/api/home_api.dart:11:16
   ╷
11 │ abstract class HomeApi {
   │                ^^^^^^^
   ╵
[SEVERE] injectable_generator:injectable_builder on lib/core/network/api/call_log_api.dart (cached):

[CallLogApi] is not a subtype of [_CallLogApi]
package:cleancodeapp/core/network/api/call_log_api.dart:13:16
   ╷
13 │ abstract class CallLogApi {
   │                ^^^^^^^^^^
   ╵
[SEVERE] injectable_generator:injectable_builder on lib/core/network/api/stripe_checkout_api.dart (cached):

[StripeCheckoutApi] is not a subtype of [_StripeCheckoutApi]
package:cleancodeapp/core/network/api/stripe_checkout_api.dart:11:16
   ╷
11 │ abstract class StripeCheckoutApi {
   │                ^^^^^^^^^^^^^^^^^
   ╵
[SEVERE] injectable_generator:injectable_builder on lib/core/network/api/auth_api.dart (cached):

[AuthApi] is not a subtype of [_AuthApi]
package:cleancodeapp/core/network/api/auth_api.dart:11:16
   ╷
11 │ abstract class AuthApi {
   │                ^^^^^^^
   ╵
[SEVERE] injectable_generator:injectable_builder on lib/core/network/api/customer_api.dart (cached):

[CustomerApi] is not a subtype of [_CustomerApi]
package:cleancodeapp/core/network/api/customer_api.dart:15:16
   ╷
15 │ abstract class CustomerApi {
   │                ^^^^^^^^^^^
   ╵
[SEVERE] injectable_generator:injectable_builder on lib/core/network/api/inventory_api.dart (cached):

[InventoryApi] is not a subtype of [_InventoryApi]
package:cleancodeapp/core/network/api/inventory_api.dart:15:16
   ╷
15 │ abstract class InventoryApi {
   │                ^^^^^^^^^^^^
   ╵
[SEVERE] injectable_generator:injectable_builder on lib/core/network/api/map_api.dart (cached):

[MapApi] is not a subtype of [_MapApi]
package:cleancodeapp/core/network/api/map_api.dart:12:16
   ╷
12 │ abstract class MapApi {
   │                ^^^^^^
   ╵
[SEVERE] Failed after 290ms

**Comment by SAGARSURI** [comment]
Stuck with the same problem! Any solution to this?

**Comment by deandreamatias** [comment]
Please, someone can take a look on this?

**Comment by deandreamatias** [comment]
> @deandreamatias have you tried using environments? injectable supports multiple environments

Hi!
Yes, but I use environments for Dev/pre/prod and can't use to diff mobile and web too

**Comment by deandreamatias** [comment]
Nice! I will try
Thanks

**Comment by deandreamatias** [comment]
@hazzo this can be useful I guess
