### ISSUE TITLE
Generated config file in test folder uses relative imports

### ISSUE THREAD

**Issue by saschaernst** [Milad-Akarie/injectable#96]
I am generating an injectable config file in my /test. But the imports are just starting like '../../some_dir_in_lib'.
It should be '../../lib/some_dir_in_lib' or preferably an absolute import.
Do I have to tweak some settings for that?

Cheers, Sascha

**Comment by Milad-Akarie** [comment]
Hey @saschaernst it's fixed in injectable_generator: 1.0.1 check it out!

**Comment by caiopo** [comment]
Hey, it's still using relative imports in my project (with injectable_generator 1.0.1).

It is also generating an invalid `import '.';`.

![image](https://user-images.githubusercontent.com/12374562/87956984-11b93400-ca86-11ea-8bd7-312789ebba52.png)

**Comment by Milad-Akarie** [comment]
@saschaernst  
@caiopo ya Sorry about that. That was one unhandled case when file path is the same as the target file path. 
Fixed in 
```yaml
injectable: 1.0.2
injectable_generator: 1.0.2
```
If you still have issues or simply don't prefer relative imports, you can use the newly added flag `preferRelativeImports` to get absolute or package imports depending on your class location.
```dart 
@InjectableInit(preferRelativeImports: false)
```

**Comment by caiopo** [comment]
It works fine now. Thank you for your quick answer and fix! This package is awesome! 😄
